name: release
true:
  release:
    types:
    - published
permissions:
  contents: read
jobs:
  pypi-publish:
    environment:
      name: pypi
      url: https://pypi.org/project/un_bound_histogram
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install build

        '
    - name: Build package
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API }}
        user: __token__
